apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mongo-pacman
  name: mongodb
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongodb
    spec:
      containers:
      - image: quay.io/jduimovich0/mongo-backend@sha256:3bfe543d08e77675dca09f53e923190eea44be0104ada5e160b817cd9a95aa1b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
